export const queryMap = {
  getUsers: "User[]",
  getUsersSearch: "User[]",
  getUsersById: { user: "User", followers: "User[]", following: "User[]" },
  getUsersByIdRepositories: "Repository[]",
  getUsersByIdTeams: "Team[]",
  getUsersByIdIssues: "Issue[]",
  getUsersByIdPullRequests: "PullRequest[]",
  getRepositories: "Repository[]",
  getRepositoriesSearch: "Repository[]",
  getRepositoriesById: {
    repository: "Repository",
    collaborators: "User[]",
    forks: "Repository[]",
  },
  getRepositoriesByIdStargazers: "User[]",
  getRepositoriesByIdIssues: "Issue[]",
  getRepositoriesByIdPullRequests: "PullRequest[]",
  getRepositoriesByIdCommits: "Commit[]",
  getIssues: "Issue[]",
  getIssuesSearch: "Issue[]",
  getIssuesById: {
    issue: "Issue",
    comments: "Comment[]",
    linkedPullRequests: "PullRequest[]",
  },
  getPullRequests: "PullRequest[]",
  getPullRequestsById: {
    pullRequest: "PullRequest",
    commits: "Commit[]",
    comments: "Comment[]",
  },
  getPullRequestsByIdReviews: "ReviewThread[]",
  getTeams: "Team[]",
  getTeamsById: {
    team: "Team",
    members: "User[]",
    subTeams: "Team[]",
    repositories: "Repository[]",
  },
  getCommitsById: {
    commit: "Commit",
    coAuthors: "User[]",
    pullRequest: "PullRequest",
  },
  getCommentsById: { comment: "Comment", replies: "Comment[]" },
  User: {
    followers: "User[]",
    following: "User[]",
    pinnedRepositories: "Repository[]",
    starredRepositories: "Repository[]",
    teams: "Team[]",
  },
  Repository: {
    owner: "User",
    collaborators: "User[]",
    stargazers: "User[]",
    forks: "Repository[]",
    parentFork: "Repository",
  },
  Team: {
    members: "User[]",
    repositories: "Repository[]",
    subTeams: "Team[]",
    parentTeam: "Team",
  },
  Issue: {
    author: "User",
    assignees: "User[]",
    comments: "Comment[]",
    linkedPullRequests: "PullRequest[]",
    repository: "Repository",
  },
  Comment: { author: "User", replies: "Comment[]", parentComment: "Comment" },
  PullRequest: {
    author: "User",
    reviewers: "User[]",
    commits: "Commit[]",
    comments: "Comment[]",
    resolvedIssues: "Issue[]",
    repository: "Repository",
  },
  Commit: { author: "User", coAuthors: "User[]", pullRequest: "PullRequest" },
  ReviewThread: {
    resolvedBy: "User",
    comments: "Comment[]",
    pullRequest: "PullRequest",
  },
} as const;

export type QueryMap = typeof queryMap;
